services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
  ingestion:
    build:
      context: .
      dockerfile: ./services/ingestion/Dockerfile
    ports: ["8080:8080"]
    volumes:
      - ingestion-data:/data
    environment:
      DATA_DIR: /data
      REDIS_ADDR: redis:6379
    restart: unless-stopped
    depends_on:
      - redis
      - init-perms
  init-perms:
    image: busybox
    command: ["sh", "-c", "chown -R 65532:65532 /data || true"]
    volumes:
      - ingestion-data:/data
    restart: "no"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
    restart: unless-stopped
    depends_on: [ingestion]
  grafana:
    image: grafana/grafana
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    ports: ["3000:3000"]
    restart: unless-stopped
    depends_on: [prometheus]
volumes:
  ingestion-data:
