name: build
on: { push: { branches: [main] } }

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build ingestion
        run: docker build -f services/ingestion/Dockerfile -t ghcr.io/medkhabt/agristant/ingestion:latest .
      - name: Push ingestion
        run: docker push ghcr.io/medkhabt/agristant/ingestion:latest
